# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'


default: &default
  adapter: mysql2
  pool: 5
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root

development:
  <<: *default
  database: test-mysql2_development