# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5977478790c93de363a845cf2dbb4eef64336faacfb70b4335784b1b17574d45f998a21c1c700254d29ee6a94f2e8a600dc587cd4c16ca8be0751dd838d3f7c3

test:
  secret_key_base: 8613608d3c9d4d866d9c7c8ca4d8d9cbbcf4cbd3753f1032cb2c4aa5d9c6ce03381843e2832e2d83ecc19284c0e1f7c04d33b5effe18d059b8304420aa3a4b64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
